//
// Created by zhouj on 2022/11/17.
//

#ifndef WWMOTOR_APP_MOTOR2_EMFZEROCROSSSECTIONSENSOR_HPP_
#define WWMOTOR_APP_MOTOR2_EMFZEROCROSSSECTIONSENSOR_HPP_

namespace wwMotor2 {

class EmfZeroCrossSectionSensor {

};

} // wwMotor2

#endif //WWMOTOR_APP_MOTOR2_EMFZEROCROSSSECTIONSENSOR_HPP_
