//
// Created by zhouj on 2022/11/17.
//

#ifndef WWMOTOR_APP_MOTOR2_FLUXOBSERVERPOSITIONSPEEDSENSOR_HPP_
#define WWMOTOR_APP_MOTOR2_FLUXOBSERVERPOSITIONSPEEDSENSOR_HPP_

namespace wwMotor2 {

class FluxObserverPositionSpeedSensor {

};

} // wwMotor2

#endif //WWMOTOR_APP_MOTOR2_FLUXOBSERVERPOSITIONSPEEDSENSOR_HPP_
