//
// Created by zhouj on 2022/11/28.
//

#ifndef WWMOTOR_APP_MOTOR2_SAMPLEPHASEVOLTAGESENSOR_HPP_
#define WWMOTOR_APP_MOTOR2_SAMPLEPHASEVOLTAGESENSOR_HPP_

namespace wwMotor2 {

class SamplePhaseVoltageSensor {

};

} // wwMotor2

#endif //WWMOTOR_APP_MOTOR2_SAMPLEPHASEVOLTAGESENSOR_HPP_
