//
// Created by zhouj on 2022/11/17.
//

#ifndef WWMOTOR_APP_MOTOR2_SHUNT3PHASECURRENTSENSOR_HPP_
#define WWMOTOR_APP_MOTOR2_SHUNT3PHASECURRENTSENSOR_HPP_

namespace wwMotor2 {

class Shunt3PhaseCurrentSensor {

};

} // wwMotor2

#endif //WWMOTOR_APP_MOTOR2_SHUNT3PHASECURRENTSENSOR_HPP_
