//
// Created by zhouj on 2022/11/16.
//

#ifndef WWMOTOR_APP_MOTOR2_POWERSENSOR_CPP_SIMPLEPOWERSENSOR_HPP_
#define WWMOTOR_APP_MOTOR2_POWERSENSOR_CPP_SIMPLEPOWERSENSOR_HPP_

#endif //WWMOTOR_APP_MOTOR2_POWERSENSOR_CPP_SIMPLEPOWERSENSOR_HPP_
